# Generated by Django 4.0.1 on 2022-01-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_item_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_text',
        ),
        migrations.AddField(
            model_name='itemdetail',
            name='item_text',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='item',
            field=models.ImageField(blank=True, upload_to='images/detail'),
        ),
    ]
