# Generated by Django 4.0.1 on 2022-01-08 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_item_item_text_itemdetail_item_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.item'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='path',
            field=models.ImageField(blank=True, upload_to='images/detail'),
        ),
    ]
